CREATE TABLE IF NOT EXISTS game_runs (
    id TEXT PRIMARY KEY NOT NULL,
    player_name TEXT NOT NULL,
    turn INTEGER NOT NULL DEFAULT 0,
    state_json TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
